# _c.f._ https://pnpm.io/settings

minimumReleaseAge: 10080 # 7 jours (exprimé en minutes)
preferFrozenLockfile: true

onlyBuiltDependencies:
  - bcrypt@6.0.0

minimumReleaseAgeExclude:
  - '@lab-anssi/lib@2.1.6'
  - axios@1.15.0
  # Renovate security update: vite@8.0.5
  - vite@8.0.5
