const risques = {
  risques: [
    {
      id: 'R2',
      intitule:
        "Compromission de ressources d'administration internes pour récupérer ou falsifier des informations et pour rendre indisponible l'activité du service",
      description:
        "Pour atteindre son objectif visé, un attaquant externe va compromettre une ressource utilisée pour l'administration technique interne.",
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut compromettre : <br>- un poste de travail d'administrateur technique,<br>- le réseau d'administration technique.",
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 4,
      categories: ['confidentialite', 'integrite', 'disponibilite'],
      mesuresAssociees: [
        'MCO_MCS.1',
        'MCO_MCS.17',
        'MCO_MCS.3',
        'MCO_MCS.4',
        'MCO_MCS.5',
        'MCO_MCS.6',
        'MCO_MCS.7',
        'CONFIG.1',
        'CONFIG.2',
        'CONFIG.6',
        'AUTH.1',
        'CONFIG.3',
        'ADMIN.4',
        'ADMIN.1',
        'ADMIN.3',
        'ADMIN.2',
        'ADMIN.5',
        'ECOSYSTEME.2',
        'ADMIN.6',
        'ADMIN.7',
        'DISTANCE.1',
        'DISTANCE.2',
        'MALWARE.3',
        'MALWARE.4',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.6',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R4',
      intitule:
        "Compromission d'un service ou d'un serveur exposé pour récupérer ou falsifier des informations et pour rendre indisponible l'activité du service",
      description:
        'Pour atteindre son objectif visé, un attaquant externe va compromettre un service ou serveur exposé.',
      exemple:
        'Par exemple, pour atteindre son objectif un attaquant externe peut exploiter une vulnérabilité applicative ou technique sur un serveur web exposé ou une API.',
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 4,
      categories: ['confidentialite', 'integrite', 'disponibilite'],
      desactive: false,
      mesuresAssociees: [
        'MCO_MCS.1',
        'MCO_MCS.17',
        'MCO_MCS.3',
        'MCO_MCS.4',
        'MCO_MCS.5',
        'MCO_MCS.6',
        'MCO_MCS.7',
        'FILTRE.7',
        'DEV.1',
        'CONFIG.1',
        'CONFIG.2',
        'CONFIG.6',
        'AUDIT.2',
        'AUDIT.3',
        'AUDIT.4',
        'AUDIT.5',
        'AUDIT.7',
        'AUDIT.6',
        'CONFIG.3',
        'CLOISON.1',
        'CLOISON.2',
        'CLOISON.3',
        'CLOISON.4',
        'CLOISON.5',
        'CLOISON.6',
        'FILTRE.1',
        'FILTRE.2',
        'FILTRE.3',
        'FILTRE.5',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.6',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R5',
      intitule:
        "Compromission d'un compte utilisateur pour récupérer ou falsifier des informations",
      description:
        "Pour atteindre son objectif visé, un attaquant externe va compromettre un compte utilisateur par ingénierie sociale ou en exploitant une faiblesse dans l'authentification.",
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut compromettre un compte via : <br>- de l'ingénierie sociale (ex. hameçonnage), <br>- une attaque par force brute sur le mécanisme d'authentification (ex. attaque par force brute ou par saisie d’authentifiants volés).",
      gravite: 1,
      graviteCalculee: 1,
      graviteeSurchargee: 1,
      vraisemblance: 4,
      categories: ['confidentialite', 'integrite'],
      desactive: false,
      mesuresAssociees: [
        'RH.2',
        'DISTANCE.2',
        'DISTANCE.4',
        'RH.4',
        'AUTH.10',
        'ID.1',
        'ID.2',
        'ID.4',
        'DROITS.1',
        'DROITS.3',
        'AUTH.11',
        'AUTH.12',
        'AUTH.4',
        'AUTH.2',
        'AUTH.3',
        'AUTH.9',
        'AUTH.8',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R6',
      intitule:
        "Compromission d'un compte d'un acteur technique interne pour récupérer ou falsifier des informations et pour rendre indisponible l'activité du service",
      description:
        "Pour atteindre son objectif visé, un attaquant externe va compromettre un compte d'un acteur technique interne (ex. administrateur, hébergeur, développeur) par ingénierie sociale ou en exploitant une faiblesse dans l'authentification.",
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut compromettre un compte via : <br>- de l'ingénierie sociale (ex. hameçonnage), <br>- une attaque par force brute sur le mécanisme d'authentification (ex. attaque par force brute ou par saisie d’authentifiants volés).",
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 4,
      categories: ['confidentialite', 'integrite', 'disponibilite'],
      mesuresAssociees: [
        'RH.2',
        'DISTANCE.2',
        'DISTANCE.4',
        'RH.4',
        'DROITS.1',
        'DROITS.3',
        'COMPADMIN.1',
        'ID.1',
        'ID.2',
        'ID.4',
        'COMPADMIN.2',
        'COMPADMIN.3',
        'COMPADMIN.4',
        'COMPADMIN.5',
        'COMPADMIN.6',
        'COMPADMIN.9',
        'AUTH.2',
        'AUTH.3',
        'AUTH.4',
        'AUTH.11',
        'AUTH.12',
        'AUTH.8',
        'AUTH.9',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.6',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R12',
      intitule:
        "Attaque DDoS sur un service exposé pour rendre indisponible l'activité du service",
      description:
        'Pour atteindre son objectif visé, un attaquant externe va réaliser une attaque par déni de service distribué (DDoS).',
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut saturer les services exposés (serveur web, API) via l'envoi d'un volume massif de requêtes depuis un réseau de machines compromises.",
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 4,
      categories: ['disponibilite'],
      mesuresAssociees: [
        'CLOISON.4',
        'FILTRE.1',
        'FILTRE.2',
        'FILTRE.3',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R13',
      intitule:
        "Compromission de ressources de développement internes pour récupérer ou falsifier des informations et pour rendre indisponible l'activité du service",
      description:
        'Pour atteindre son objectif visé, un attaquant externe va compromettre une ressource interne (ex. CI/CD) utilisée pour le développement.',
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut compromettre :<br>- la chaîne d'intégration et de déploiement (CI/CD),<br>- un dépôt de code source.",
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 4,
      categories: ['confidentialite', 'integrite', 'disponibilite'],
      mesuresAssociees: [
        'DEV.1',
        'AUDIT.6',
        'AUDIT.2',
        'ECOSYSTEME.2',
        'CLOISON.3',
        'CONFIG.1',
        'CONFIG.2',
        'CONFIG.3',
        'CONFIG.6',
        'MCO_MCS.1',
        'MCO_MCS.17',
        'MCO_MCS.3',
        'MCO_MCS.4',
        'MCO_MCS.5',
        'MCO_MCS.6',
        'MCO_MCS.7',
        'DISTANCE.2',
        'AUTH.4',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.6',
        'SUPERVISION.7',
      ],
    },
  ],
  risquesBruts: [
    {
      id: 'R2',
      intitule:
        "Compromission de ressources d'administration internes pour récupérer ou falsifier des informations et pour rendre indisponible l'activité du service",
      description:
        "Pour atteindre son objectif visé, un attaquant externe va compromettre une ressource utilisée pour l'administration technique interne.",
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut compromettre : <br>- un poste de travail d'administrateur technique,<br>- le réseau d'administration technique.",
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 4,
      categories: ['confidentialite', 'integrite', 'disponibilite'],
      mesuresAssociees: [
        'MCO_MCS.1',
        'MCO_MCS.17',
        'MCO_MCS.3',
        'MCO_MCS.4',
        'MCO_MCS.5',
        'MCO_MCS.6',
        'MCO_MCS.7',
        'CONFIG.1',
        'CONFIG.2',
        'CONFIG.6',
        'AUTH.1',
        'CONFIG.3',
        'ADMIN.4',
        'ADMIN.1',
        'ADMIN.3',
        'ADMIN.2',
        'ADMIN.5',
        'ECOSYSTEME.2',
        'ADMIN.6',
        'ADMIN.7',
        'DISTANCE.1',
        'DISTANCE.2',
        'MALWARE.3',
        'MALWARE.4',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.6',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R4',
      intitule:
        "Compromission d'un service ou d'un serveur exposé pour récupérer ou falsifier des informations et pour rendre indisponible l'activité du service",
      description:
        'Pour atteindre son objectif visé, un attaquant externe va compromettre un service ou serveur exposé.',
      exemple:
        'Par exemple, pour atteindre son objectif un attaquant externe peut exploiter une vulnérabilité applicative ou technique sur un serveur web exposé ou une API.',
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 4,
      categories: ['confidentialite', 'integrite', 'disponibilite'],
      desactive: false,
      mesuresAssociees: [
        'MCO_MCS.1',
        'MCO_MCS.17',
        'MCO_MCS.3',
        'MCO_MCS.4',
        'MCO_MCS.5',
        'MCO_MCS.6',
        'MCO_MCS.7',
        'FILTRE.7',
        'DEV.1',
        'CONFIG.1',
        'CONFIG.2',
        'CONFIG.6',
        'AUDIT.2',
        'AUDIT.3',
        'AUDIT.4',
        'AUDIT.5',
        'AUDIT.7',
        'AUDIT.6',
        'CONFIG.3',
        'CLOISON.1',
        'CLOISON.2',
        'CLOISON.3',
        'CLOISON.4',
        'CLOISON.5',
        'CLOISON.6',
        'FILTRE.1',
        'FILTRE.2',
        'FILTRE.3',
        'FILTRE.5',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.6',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R5',
      intitule:
        "Compromission d'un compte utilisateur pour récupérer ou falsifier des informations",
      description:
        "Pour atteindre son objectif visé, un attaquant externe va compromettre un compte utilisateur par ingénierie sociale ou en exploitant une faiblesse dans l'authentification.",
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut compromettre un compte via : <br>- de l'ingénierie sociale (ex. hameçonnage), <br>- une attaque par force brute sur le mécanisme d'authentification (ex. attaque par force brute ou par saisie d’authentifiants volés).",
      gravite: 1,
      graviteCalculee: 1,
      graviteeSurchargee: 1,
      vraisemblance: 4,
      categories: ['confidentialite', 'integrite'],
      desactive: false,
      mesuresAssociees: [
        'RH.2',
        'DISTANCE.2',
        'DISTANCE.4',
        'RH.4',
        'AUTH.10',
        'ID.1',
        'ID.2',
        'ID.4',
        'DROITS.1',
        'DROITS.3',
        'AUTH.11',
        'AUTH.12',
        'AUTH.4',
        'AUTH.2',
        'AUTH.3',
        'AUTH.9',
        'AUTH.8',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R6',
      intitule:
        "Compromission d'un compte d'un acteur technique interne pour récupérer ou falsifier des informations et pour rendre indisponible l'activité du service",
      description:
        "Pour atteindre son objectif visé, un attaquant externe va compromettre un compte d'un acteur technique interne (ex. administrateur, hébergeur, développeur) par ingénierie sociale ou en exploitant une faiblesse dans l'authentification.",
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut compromettre un compte via : <br>- de l'ingénierie sociale (ex. hameçonnage), <br>- une attaque par force brute sur le mécanisme d'authentification (ex. attaque par force brute ou par saisie d’authentifiants volés).",
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 4,
      categories: ['confidentialite', 'integrite', 'disponibilite'],
      mesuresAssociees: [
        'RH.2',
        'DISTANCE.2',
        'DISTANCE.4',
        'RH.4',
        'DROITS.1',
        'DROITS.3',
        'COMPADMIN.1',
        'ID.1',
        'ID.2',
        'ID.4',
        'COMPADMIN.2',
        'COMPADMIN.3',
        'COMPADMIN.4',
        'COMPADMIN.5',
        'COMPADMIN.6',
        'COMPADMIN.9',
        'AUTH.2',
        'AUTH.3',
        'AUTH.4',
        'AUTH.11',
        'AUTH.12',
        'AUTH.8',
        'AUTH.9',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.6',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R12',
      intitule:
        "Attaque DDoS sur un service exposé pour rendre indisponible l'activité du service",
      description:
        'Pour atteindre son objectif visé, un attaquant externe va réaliser une attaque par déni de service distribué (DDoS).',
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut saturer les services exposés (serveur web, API) via l'envoi d'un volume massif de requêtes depuis un réseau de machines compromises.",
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 4,
      categories: ['disponibilite'],
      mesuresAssociees: [
        'CLOISON.4',
        'FILTRE.1',
        'FILTRE.2',
        'FILTRE.3',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R13',
      intitule:
        "Compromission de ressources de développement internes pour récupérer ou falsifier des informations et pour rendre indisponible l'activité du service",
      description:
        'Pour atteindre son objectif visé, un attaquant externe va compromettre une ressource interne (ex. CI/CD) utilisée pour le développement.',
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut compromettre :<br>- la chaîne d'intégration et de déploiement (CI/CD),<br>- un dépôt de code source.",
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 4,
      categories: ['confidentialite', 'integrite', 'disponibilite'],
      mesuresAssociees: [
        'DEV.1',
        'AUDIT.6',
        'AUDIT.2',
        'ECOSYSTEME.2',
        'CLOISON.3',
        'CONFIG.1',
        'CONFIG.2',
        'CONFIG.3',
        'CONFIG.6',
        'MCO_MCS.1',
        'MCO_MCS.17',
        'MCO_MCS.3',
        'MCO_MCS.4',
        'MCO_MCS.5',
        'MCO_MCS.6',
        'MCO_MCS.7',
        'DISTANCE.2',
        'AUTH.4',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.6',
        'SUPERVISION.7',
      ],
    },
  ],
  risquesCibles: [
    {
      id: 'R2',
      intitule:
        "Compromission de ressources d'administration internes pour récupérer ou falsifier des informations et pour rendre indisponible l'activité du service",
      description:
        "Pour atteindre son objectif visé, un attaquant externe va compromettre une ressource utilisée pour l'administration technique interne.",
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut compromettre : <br>- un poste de travail d'administrateur technique,<br>- le réseau d'administration technique.",
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 1,
      categories: ['confidentialite', 'integrite', 'disponibilite'],
      mesuresAssociees: [
        'MCO_MCS.1',
        'MCO_MCS.17',
        'MCO_MCS.3',
        'MCO_MCS.4',
        'MCO_MCS.5',
        'MCO_MCS.6',
        'MCO_MCS.7',
        'CONFIG.1',
        'CONFIG.2',
        'CONFIG.6',
        'AUTH.1',
        'CONFIG.3',
        'ADMIN.4',
        'ADMIN.1',
        'ADMIN.3',
        'ADMIN.2',
        'ADMIN.5',
        'ECOSYSTEME.2',
        'ADMIN.6',
        'ADMIN.7',
        'DISTANCE.1',
        'DISTANCE.2',
        'MALWARE.3',
        'MALWARE.4',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.6',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R4',
      intitule:
        "Compromission d'un service ou d'un serveur exposé pour récupérer ou falsifier des informations et pour rendre indisponible l'activité du service",
      description:
        'Pour atteindre son objectif visé, un attaquant externe va compromettre un service ou serveur exposé.',
      exemple:
        'Par exemple, pour atteindre son objectif un attaquant externe peut exploiter une vulnérabilité applicative ou technique sur un serveur web exposé ou une API.',
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 2,
      categories: ['confidentialite', 'integrite', 'disponibilite'],
      desactive: false,
      mesuresAssociees: [
        'MCO_MCS.1',
        'MCO_MCS.17',
        'MCO_MCS.3',
        'MCO_MCS.4',
        'MCO_MCS.5',
        'MCO_MCS.6',
        'MCO_MCS.7',
        'FILTRE.7',
        'DEV.1',
        'CONFIG.1',
        'CONFIG.2',
        'CONFIG.6',
        'AUDIT.2',
        'AUDIT.3',
        'AUDIT.4',
        'AUDIT.5',
        'AUDIT.7',
        'AUDIT.6',
        'CONFIG.3',
        'CLOISON.1',
        'CLOISON.2',
        'CLOISON.3',
        'CLOISON.4',
        'CLOISON.5',
        'CLOISON.6',
        'FILTRE.1',
        'FILTRE.2',
        'FILTRE.3',
        'FILTRE.5',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.6',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R5',
      intitule:
        "Compromission d'un compte utilisateur pour récupérer ou falsifier des informations",
      description:
        "Pour atteindre son objectif visé, un attaquant externe va compromettre un compte utilisateur par ingénierie sociale ou en exploitant une faiblesse dans l'authentification.",
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut compromettre un compte via : <br>- de l'ingénierie sociale (ex. hameçonnage), <br>- une attaque par force brute sur le mécanisme d'authentification (ex. attaque par force brute ou par saisie d’authentifiants volés).",
      gravite: 1,
      graviteCalculee: 1,
      graviteeSurchargee: 1,
      vraisemblance: 1,
      categories: ['confidentialite', 'integrite'],
      desactive: false,
      mesuresAssociees: [
        'RH.2',
        'DISTANCE.2',
        'DISTANCE.4',
        'RH.4',
        'AUTH.10',
        'ID.1',
        'ID.2',
        'ID.4',
        'DROITS.1',
        'DROITS.3',
        'AUTH.11',
        'AUTH.12',
        'AUTH.4',
        'AUTH.2',
        'AUTH.3',
        'AUTH.9',
        'AUTH.8',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R6',
      intitule:
        "Compromission d'un compte d'un acteur technique interne pour récupérer ou falsifier des informations et pour rendre indisponible l'activité du service",
      description:
        "Pour atteindre son objectif visé, un attaquant externe va compromettre un compte d'un acteur technique interne (ex. administrateur, hébergeur, développeur) par ingénierie sociale ou en exploitant une faiblesse dans l'authentification.",
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut compromettre un compte via : <br>- de l'ingénierie sociale (ex. hameçonnage), <br>- une attaque par force brute sur le mécanisme d'authentification (ex. attaque par force brute ou par saisie d’authentifiants volés).",
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 1,
      categories: ['confidentialite', 'integrite', 'disponibilite'],
      mesuresAssociees: [
        'RH.2',
        'DISTANCE.2',
        'DISTANCE.4',
        'RH.4',
        'DROITS.1',
        'DROITS.3',
        'COMPADMIN.1',
        'ID.1',
        'ID.2',
        'ID.4',
        'COMPADMIN.2',
        'COMPADMIN.3',
        'COMPADMIN.4',
        'COMPADMIN.5',
        'COMPADMIN.6',
        'COMPADMIN.9',
        'AUTH.2',
        'AUTH.3',
        'AUTH.4',
        'AUTH.11',
        'AUTH.12',
        'AUTH.8',
        'AUTH.9',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.6',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R12',
      intitule:
        "Attaque DDoS sur un service exposé pour rendre indisponible l'activité du service",
      description:
        'Pour atteindre son objectif visé, un attaquant externe va réaliser une attaque par déni de service distribué (DDoS).',
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut saturer les services exposés (serveur web, API) via l'envoi d'un volume massif de requêtes depuis un réseau de machines compromises.",
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 1,
      categories: ['disponibilite'],
      mesuresAssociees: [
        'CLOISON.4',
        'FILTRE.1',
        'FILTRE.2',
        'FILTRE.3',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.7',
      ],
    },
    {
      id: 'R13',
      intitule:
        "Compromission de ressources de développement internes pour récupérer ou falsifier des informations et pour rendre indisponible l'activité du service",
      description:
        'Pour atteindre son objectif visé, un attaquant externe va compromettre une ressource interne (ex. CI/CD) utilisée pour le développement.',
      exemple:
        "Par exemple, pour atteindre son objectif un attaquant externe peut compromettre :<br>- la chaîne d'intégration et de déploiement (CI/CD),<br>- un dépôt de code source.",
      gravite: 1,
      graviteCalculee: 1,
      vraisemblance: 1,
      categories: ['confidentialite', 'integrite', 'disponibilite'],
      mesuresAssociees: [
        'DEV.1',
        'AUDIT.6',
        'AUDIT.2',
        'ECOSYSTEME.2',
        'CLOISON.3',
        'CONFIG.1',
        'CONFIG.2',
        'CONFIG.3',
        'CONFIG.6',
        'MCO_MCS.1',
        'MCO_MCS.17',
        'MCO_MCS.3',
        'MCO_MCS.4',
        'MCO_MCS.5',
        'MCO_MCS.6',
        'MCO_MCS.7',
        'DISTANCE.2',
        'AUTH.4',
        'SUPERVISION.4',
        'SUPERVISION.5',
        'SUPERVISION.6',
        'SUPERVISION.7',
      ],
    },
  ],
  risquesSpecifiques: [
    {
      id: 'a99aa881-0c03-4a7b-90b3-0b908a33d727',
      intitule: 'Un risque spé',
      identifiantNumerique: 'RS1',
      description: '',
      categories: ['disponibilite'],
      gravite: 1,
      vraisemblance: 1,
      graviteBrute: 1,
      vraisemblanceBrute: 1,
      commentaire: 'efazf',
    },
  ],
};

export const donneesVisiteGuidee = { risques };
