# Vérification des recommandations CIS et autres sur les configurations GitHub
# https://www.checkov.io/1.Welcome/What%20is%20Checkov.html
# https://github.com/bridgecrewio/checkov-action
---
name: checkov
permissions: {}
on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['main', 'master']

  workflow_dispatch:

jobs:
  scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3

        if: success() || failure()
        with:
          sarif_file: results.sarif
