name: Déploiement vers un environnement de DEV
permissions: {}
on:
  workflow_dispatch: # Pour activer le déclenchement manuel

jobs:
  deploiement-dev:
    name: Déploiement en DEV
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Cloner l'intégralité du dépôt, pour ne pas avoir de « shallow repo » rejeté par Clever

      - name: Installer la CLI Clever Cloud
        shell: bash
        run: npm install -g clever-tools

      - name: Spécifier la version de Node.js à utiliser auprès de Clever Cloud
        env:
          CLEVER_SECRET: ${{ secrets.CLEVER_CLOUD_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_CLOUD_TOKEN }}
          ID_APP: ${{ secrets.CLEVER_CLOUD_ID_APP }}
          ID_ORGANISATION: ${{ secrets.CLEVER_CLOUD_ID_ORGANISATION }}
        run: |
          NODE_VERSION="$(./scripts/get-node-version.sh)"
          clever link -o="$ID_ORGANISATION" "$ID_APP"
          clever env set CC_NODE_VERSION "$NODE_VERSION"

      - name: Déployer en DEV
        env:
          CLEVER_SECRET: ${{ secrets.CLEVER_CLOUD_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_CLOUD_TOKEN }}
          ID_APP: ${{ secrets.CLEVER_CLOUD_ID_APP }}
          ID_ORGANISATION: ${{ secrets.CLEVER_CLOUD_ID_ORGANISATION }}
        run: |
          clever link -o="$ID_ORGANISATION" "$ID_APP"
          clever deploy --force --same-commit-policy=rebuild
