name: Déploiement
run-name: Déploiement du commit "${{ github.event.head_commit.message }}"
permissions: {}

on:
  push:
    branches: [master]
  workflow_dispatch: # Pour activer le déclenchement manuel

jobs:
  deploiement-demo:
    name: Déploiement en DÉMO
    uses: ./.github/workflows/deploiement-clever-cloud.yml
    with:
      environment: DEMO
    secrets: inherit

  deploiement-prod:
    needs: [deploiement-demo]
    name: Déploiement en PROD
    uses: ./.github/workflows/deploiement-clever-cloud.yml
    with:
      environment: PROD
    secrets: inherit
