name: Déploiement vers un environnement de DEV
permissions: {}

on:
  workflow_dispatch: # Pour activer le déclenchement manuel

jobs:
  deploiement-dev:
    name: Déploiement en DEV
    uses: ./.github/workflows/deploiement-clever-cloud.yml
    with:
      environment: DEV
    secrets: inherit
