name: renovate
permissions: {}
on:
  pull_request:
    branches: ['master']

  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Lance la github action Renovate
        uses: renovatebot/github-action@v46.1.9
        with:
          configurationFile: .renovate/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
